### ISSUE TITLE
V.S. https://hl7.org/fhir/rdf.html 

### ISSUE THREAD

**Issue by xdxxxdx** [smart-data-models/dataModel.Hl7#1]
Hello @Fiware team,

According to there is a mapping form HI7 itself for https://hl7.org/fhir/rdf.html for FHIR, what is the relationship between fiware smart data model and https://hl7.org/fhir/rdf.html? 

Thanks

**Comment by albertoabellagarcia** [comment]
As stated in the schema.json these data models are derived from [http://hl7.org/fhir/R4B/](http://hl7.org/fhir/R4B/) 

so basically they are coming from the link you provide

**Comment by albertoabellagarcia** [comment]
And sorry for the delay in the answer
